#!/bin/bash
# ========================================================================
# CRÉATION DES TABLES CRITIQUES MANQUANTES
# ========================================================================

set -e

echo "════════════════════════════════════════════════════════════════════════"
echo "🔧 CRÉATION DES TABLES CRITIQUES MANQUANTES"
echo "════════════════════════════════════════════════════════════════════════"
echo ""

echo "📊 Tables critiques à créer:"
echo "   1. ai_cost_tracking (tracking détaillé des coûts IA)"
echo "   2. ai_prompt_templates (templates de prompts)"
echo "   3. ai_prompt_usage (usage des prompts)"
echo "   4. task_update_triggers (triggers de mise à jour)"
echo ""

# Vérifier que Docker est lancé
if ! docker ps | grep -q "ai_agent_postgres"; then
    echo "❌ Le conteneur PostgreSQL n'est pas démarré"
    exit 1
fi

echo "✅ Conteneur PostgreSQL détecté"
echo ""

# Étape 1: Créer schema_complet_ai_agent pour avoir ai_cost_tracking
echo "📦 Étape 1: Création de ai_cost_tracking"
echo "────────────────────────────────────────────────────────────────────────"
docker exec -i ai_agent_postgres psql -U admin -d ai_agent_admin <<'EOF'
-- Créer uniquement ai_cost_tracking si elle n'existe pas
CREATE TABLE IF NOT EXISTS ai_cost_tracking (
    ai_cost_tracking_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT REFERENCES tasks(tasks_id) ON DELETE CASCADE,
    task_run_id BIGINT REFERENCES task_runs(tasks_runs_id) ON DELETE CASCADE,
    provider VARCHAR(50) NOT NULL,
    model VARCHAR(100) NOT NULL,
    operation_type VARCHAR(50),
    prompt_tokens INTEGER NOT NULL,
    completion_tokens INTEGER NOT NULL,
    total_tokens INTEGER NOT NULL,
    cost_usd NUMERIC(12,6) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ai_cost_task ON ai_cost_tracking(task_id);
CREATE INDEX IF NOT EXISTS idx_ai_cost_run ON ai_cost_tracking(task_run_id);
CREATE INDEX IF NOT EXISTS idx_ai_cost_provider_date ON ai_cost_tracking(provider, created_at DESC);

COMMENT ON TABLE ai_cost_tracking IS 'Tracking des coûts d''utilisation des API IA';

\echo '✅ Table ai_cost_tracking créée'
EOF

# Étape 2: Créer les tables conversationnelles
echo ""
echo "📦 Étape 2: Création des tables conversationnelles (prompts, etc.)"
echo "────────────────────────────────────────────────────────────────────────"
docker exec -i ai_agent_postgres psql -U admin -d ai_agent_admin < data/migration_conversational_features.sql 2>&1 | grep -E "CREATE TABLE|ERROR|✅" || echo "✅ Migration conversationnelle appliquée"

# Étape 3: Créer task_update_triggers
echo ""
echo "📦 Étape 3: Création de task_update_triggers"
echo "────────────────────────────────────────────────────────────────────────"
docker exec -i ai_agent_postgres psql -U admin -d ai_agent_admin < data/migration_task_update_triggers.sql 2>&1 | grep -E "CREATE TABLE|ERROR|✅" || echo "✅ Table task_update_triggers créée"

# Étape 4: Vérification finale
echo ""
echo "📦 Étape 4: Vérification des tables créées"
echo "────────────────────────────────────────────────────────────────────────"
docker exec ai_agent_postgres psql -U admin -d ai_agent_admin -c "
SELECT 
    tablename,
    CASE 
        WHEN tablename IN ('ai_cost_tracking', 'ai_prompt_templates', 'ai_prompt_usage', 'task_update_triggers') 
        THEN '✅ NOUVELLE TABLE CRITIQUE'
        ELSE '📊 Existante'
    END as status
FROM pg_tables 
WHERE schemaname = 'public'
AND tablename IN ('ai_cost_tracking', 'ai_prompt_templates', 'ai_prompt_usage', 'task_update_triggers', 'task_context_memory')
ORDER BY tablename;
"

echo ""
echo "════════════════════════════════════════════════════════════════════════"
echo "✅ CRÉATION TERMINÉE"
echo "════════════════════════════════════════════════════════════════════════"
echo ""
echo "🔍 Relancer la vérification complète:"
echo "   ./venv/bin/python verify_all_tables.py"
echo ""

