-- ========================================================================
-- CRÉATION DE LA TABLE webhook_events (Partitionnée)
-- ========================================================================
-- Cette table est nécessaire pour enregistrer les webhooks de Monday.com
-- Elle est partitionnée par mois pour optimiser les performances
-- ========================================================================

-- Supprimer la table si elle existe déjà (pour réinitialisation)
DROP TABLE IF EXISTS webhook_events CASCADE;

-- Créer la table principale (partitionnée par date)
CREATE TABLE webhook_events (
    webhook_events_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    source VARCHAR(50) NOT NULL,
    event_type VARCHAR(100),
    payload JSONB NOT NULL,
    headers JSONB,
    signature TEXT,
    processed BOOLEAN NOT NULL DEFAULT FALSE,
    processing_status VARCHAR(50) NOT NULL DEFAULT 'pending',
    error_message TEXT,
    related_task_id BIGINT,
    received_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    processed_at TIMESTAMPTZ,
    PRIMARY KEY (webhook_events_id, received_at)
) PARTITION BY RANGE (received_at);

COMMENT ON TABLE webhook_events IS 'Événements webhook reçus (Monday.com, GitHub, etc.) - Table partitionnée par mois';

-- Créer les partitions pour les derniers et prochains mois
-- Septembre 2025
CREATE TABLE IF NOT EXISTS webhook_events_2025_09
    PARTITION OF webhook_events
    FOR VALUES FROM ('2025-09-01') TO ('2025-10-01');

-- Octobre 2025 (mois actuel)
CREATE TABLE IF NOT EXISTS webhook_events_2025_10
    PARTITION OF webhook_events
    FOR VALUES FROM ('2025-10-01') TO ('2025-11-01');

-- Novembre 2025 (mois prochain)
CREATE TABLE IF NOT EXISTS webhook_events_2025_11
    PARTITION OF webhook_events
    FOR VALUES FROM ('2025-11-01') TO ('2025-12-01');

-- Décembre 2025
CREATE TABLE IF NOT EXISTS webhook_events_2025_12
    PARTITION OF webhook_events
    FOR VALUES FROM ('2025-12-01') TO ('2026-01-01');

-- Index sur la partition d'octobre 2025 (mois actuel)
CREATE INDEX IF NOT EXISTS idx_webhook_events_processed_2025_10 
    ON webhook_events_2025_10(processed, received_at);

CREATE INDEX IF NOT EXISTS idx_webhook_events_source_2025_10 
    ON webhook_events_2025_10(source, event_type);

CREATE INDEX IF NOT EXISTS idx_webhook_events_task_2025_10 
    ON webhook_events_2025_10(related_task_id);

-- Index sur la partition de novembre 2025
CREATE INDEX IF NOT EXISTS idx_webhook_events_processed_2025_11 
    ON webhook_events_2025_11(processed, received_at);

CREATE INDEX IF NOT EXISTS idx_webhook_events_source_2025_11 
    ON webhook_events_2025_11(source, event_type);

CREATE INDEX IF NOT EXISTS idx_webhook_events_task_2025_11 
    ON webhook_events_2025_11(related_task_id);

-- Index sur la partition de décembre 2025
CREATE INDEX IF NOT EXISTS idx_webhook_events_processed_2025_12 
    ON webhook_events_2025_12(processed, received_at);

CREATE INDEX IF NOT EXISTS idx_webhook_events_source_2025_12 
    ON webhook_events_2025_12(source, event_type);

CREATE INDEX IF NOT EXISTS idx_webhook_events_task_2025_12 
    ON webhook_events_2025_12(related_task_id);

-- Vérification
DO $$
DECLARE
    partition_name text;
    partition_count integer := 0;
BEGIN
    RAISE NOTICE '========================================================================';
    RAISE NOTICE '✅ TABLE webhook_events CRÉÉE AVEC SUCCÈS';
    RAISE NOTICE '========================================================================';
    RAISE NOTICE '';
    RAISE NOTICE '📋 Partitions créées:';
    
    FOR partition_name IN 
        SELECT tablename 
        FROM pg_tables 
        WHERE schemaname = 'public' 
        AND tablename LIKE 'webhook_events_%'
        ORDER BY tablename
    LOOP
        partition_count := partition_count + 1;
        RAISE NOTICE '   • %', partition_name;
    END LOOP;
    
    RAISE NOTICE '';
    RAISE NOTICE '📊 Total: % partitions', partition_count;
    RAISE NOTICE '';
    RAISE NOTICE '✅ La table est prête à recevoir les webhooks Monday.com';
    RAISE NOTICE '========================================================================';
END $$;

