-- Migration: Création de la table run_step_checkpoints
-- Date: 2025-10-02
-- Objectif: Corriger l'erreur "relation run_step_checkpoints does not exist"

-- Créer la table run_step_checkpoints si elle n'existe pas
CREATE TABLE IF NOT EXISTS run_step_checkpoints (
    checkpoint_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    step_id BIGINT NOT NULL REFERENCES run_steps(run_steps_id) ON DELETE CASCADE,
    checkpoint_data JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ
);

-- Créer les index pour optimiser les performances
CREATE INDEX IF NOT EXISTS idx_checkpoints_step_id ON run_step_checkpoints(step_id);
CREATE INDEX IF NOT EXISTS idx_checkpoints_created_at ON run_step_checkpoints(created_at DESC);

-- Afficher un message de confirmation
DO $$
BEGIN
    RAISE NOTICE '✅ Table run_step_checkpoints créée avec succès';
END $$;

