"""
Script pour s'assurer que la table run_step_checkpoints existe.
Ce script vérifie et crée la table si elle n'existe pas.
"""

import asyncio
import asyncpg
import sys
import os
from dotenv import load_dotenv

# Charger les variables d'environnement
load_dotenv()

# Récupérer l'URL de la base de données
DATABASE_URL = os.getenv("DATABASE_URL", "postgresql://admin:password@localhost:5432/ai_agent_admin")


async def ensure_checkpoints_table():
    """Vérifie et crée la table run_step_checkpoints si nécessaire."""
    
    conn = None
    
    try:
        print("🔗 Connexion à la base de données...")
        conn = await asyncpg.connect(DATABASE_URL)
        
        # Vérifier si la table existe
        table_exists = await conn.fetchval("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'run_step_checkpoints'
            )
        """)
        
        if table_exists:
            print("✅ La table run_step_checkpoints existe déjà")
            
            # Vérifier le nombre d'enregistrements
            count = await conn.fetchval("SELECT COUNT(*) FROM run_step_checkpoints")
            print(f"📊 Nombre de checkpoints existants: {count}")
            return True
        
        print("⚠️ La table run_step_checkpoints n'existe pas - Création...")
        
        # Créer la table run_step_checkpoints
        await conn.execute("""
            CREATE TABLE IF NOT EXISTS run_step_checkpoints (
                checkpoint_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                step_id BIGINT NOT NULL REFERENCES run_steps(run_steps_id) ON DELETE CASCADE,
                checkpoint_data JSONB,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ
            )
        """)
        
        print("✅ Table run_step_checkpoints créée")
        
        # Créer les index
        await conn.execute("""
            CREATE INDEX IF NOT EXISTS idx_checkpoints_step_id 
            ON run_step_checkpoints(step_id)
        """)
        
        await conn.execute("""
            CREATE INDEX IF NOT EXISTS idx_checkpoints_created_at 
            ON run_step_checkpoints(created_at DESC)
        """)
        
        print("✅ Index créés")
        
        # Vérifier que tout est OK
        table_exists_now = await conn.fetchval("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'run_step_checkpoints'
            )
        """)
        
        if table_exists_now:
            print("✅ Table run_step_checkpoints créée avec succès")
            return True
        else:
            print("❌ Échec de la création de la table")
            return False
            
    except asyncpg.exceptions.UndefinedTableError as e:
        print(f"❌ Table run_steps n'existe pas: {e}")
        print("💡 Exécutez d'abord: psql $DATABASE_URL -f data/base2.sql")
        return False
        
    except Exception as e:
        print(f"❌ Erreur lors de la vérification/création: {e}")
        import traceback
        traceback.print_exc()
        return False
        
    finally:
        if conn:
            await conn.close()
            print("🔒 Connexion fermée")


async def verify_run_steps_table():
    """Vérifie que la table run_steps existe avec les bonnes colonnes."""
    
    conn = None
    
    try:
        conn = await asyncpg.connect(DATABASE_URL)
        
        # Vérifier que run_steps existe
        table_exists = await conn.fetchval("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'run_steps'
            )
        """)
        
        if not table_exists:
            print("❌ La table run_steps n'existe pas")
            print("💡 Exécutez: psql $DATABASE_URL -f data/base2.sql")
            return False
        
        print("✅ La table run_steps existe")
        
        # Vérifier les colonnes checkpoint_data et checkpoint_saved_at
        columns = await conn.fetch("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'run_steps' 
            AND column_name IN ('checkpoint_data', 'checkpoint_saved_at')
        """)
        
        column_names = [row['column_name'] for row in columns]
        
        if 'checkpoint_data' not in column_names:
            print("⚠️ Colonne checkpoint_data manquante - Ajout...")
            await conn.execute("ALTER TABLE run_steps ADD COLUMN checkpoint_data JSONB")
            print("✅ Colonne checkpoint_data ajoutée")
        else:
            print("✅ Colonne checkpoint_data existe")
        
        if 'checkpoint_saved_at' not in column_names:
            print("⚠️ Colonne checkpoint_saved_at manquante - Ajout...")
            await conn.execute("ALTER TABLE run_steps ADD COLUMN checkpoint_saved_at TIMESTAMPTZ")
            print("✅ Colonne checkpoint_saved_at ajoutée")
        else:
            print("✅ Colonne checkpoint_saved_at existe")
        
        return True
        
    except Exception as e:
        print(f"❌ Erreur lors de la vérification de run_steps: {e}")
        import traceback
        traceback.print_exc()
        return False
        
    finally:
        if conn:
            await conn.close()


async def main():
    """Point d'entrée principal."""
    
    print("\n" + "="*60)
    print("🔧 Vérification et création de la table run_step_checkpoints")
    print("="*60 + "\n")
    
    # 1. Vérifier la table run_steps
    print("📋 Étape 1/2: Vérification de la table run_steps...")
    run_steps_ok = await verify_run_steps_table()
    
    if not run_steps_ok:
        print("❌ La table run_steps doit exister avant de créer run_step_checkpoints")
        print("💡 Exécutez: psql $DATABASE_URL -f data/base2.sql")
        return False
    
    print()
    
    # 2. Créer la table run_step_checkpoints
    print("📋 Étape 2/2: Création de la table run_step_checkpoints...")
    checkpoints_ok = await ensure_checkpoints_table()
    
    print("\n" + "="*60)
    if checkpoints_ok:
        print("✅ Configuration terminée avec succès!")
        print("="*60 + "\n")
        return True
    else:
        print("❌ Échec de la configuration")
        print("="*60 + "\n")
        return False


if __name__ == "__main__":
    success = asyncio.run(main())
    sys.exit(0 if success else 1)

